[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["scatter_gather"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "scatter_gather"
  org = "asankaabeyweeradshvl"
  version = "3.1.1"

